version: '3'

services:
  ui:
    build:
      context: ./client
    # command: npm start
    volumes:
      - ./client:/app:rw
      - node_modules:/src/node_modules
    ports:
      - '5000:5000'
      - '5001:5001'
    # networks:
    #   - front-tier
    #   - back-tier

volumes:
  node_modules:
# networks:
#   front-tier:
#   back-tier:
