// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "./../../../node_modules/reason-react/lib/es6_global/src/ReactDOMRe.js";
import * as ReasonReact from "./../../../node_modules/reason-react/lib/es6_global/src/ReasonReact.js";
import * as App$ReactTemplate from "./App.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make(undefined, /* array */[])), "main");

export {
  
}
/*  Not a pure module */
