[package]
name = "blue-coin-services"
version = "0.1.0"
authors = ["Ryan Chan <rychan14@gmail.com>"]

[dependencies]
env_logger = "0.6"

actix = "0.7"
actix-web = "0.7"
dotenv = "0.13.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

listenfd = "0.3"

[build-dependencies]
askama = "0.7"